version: "3.9"
services:
  registration_server:
    hostname: register
    container_name: register
    build:
      context: .
      dockerfile: ./DockerFile/server_register
    ports:
      - 8000:8000
    environment:
      - REPLICHE=3
    networks:
      - mynetwork
  nodo8101:
    container_name: nodo8101
    hostname: nodo8101
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8101:8005
    environment:
      - PORT_EXSPOST=8101
      - CODICE_HASH=8001
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8102:
    container_name: nodo8102
    hostname: nodo8102
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8102:8005
    environment:
      - PORT_EXSPOST=8102
      - CODICE_HASH=8001
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8103:
    container_name: nodo8103
    hostname: nodo8103
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8103:8005
    environment:
      - PORT_EXSPOST=8103
      - CODICE_HASH=8001
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8201:
    container_name: nodo8201
    hostname: nodo8201
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8201:8005
    environment:
      - PORT_EXSPOST=8201
      - CODICE_HASH=8002
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8202:
    container_name: nodo8202
    hostname: nodo8202
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8202:8005
    environment:
      - PORT_EXSPOST=8202
      - CODICE_HASH=8002
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8203:
    container_name: nodo8203
    hostname: nodo8203
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8203:8005
    environment:
      - PORT_EXSPOST=8203
      - CODICE_HASH=8002
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8301:
    container_name: nodo8301
    hostname: nodo8301
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8301:8005
    environment:
      - PORT_EXSPOST=8301
      - CODICE_HASH=8003
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8302:
    container_name: nodo8302
    hostname: nodo8302
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8302:8005
    environment:
      - PORT_EXSPOST=8302
      - CODICE_HASH=8003
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8303:
    container_name: nodo8303
    hostname: nodo8303
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8303:8005
    environment:
      - PORT_EXSPOST=8303
      - CODICE_HASH=8003
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8401:
    container_name: nodo8401
    hostname: nodo8401
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8401:8005
    environment:
      - PORT_EXSPOST=8401
      - CODICE_HASH=8004
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8402:
    container_name: nodo8402
    hostname: nodo8402
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8402:8005
    environment:
      - PORT_EXSPOST=8402
      - CODICE_HASH=8004
    depends_on:
      - registration_server
    networks:
      - mynetwork
  nodo8403:
    container_name: nodo8403
    hostname: nodo8403
    build:
      context: .
      dockerfile: ./DockerFile/nodo
    ports:
      - 8403:8005
    environment:
      - PORT_EXSPOST=8403
      - CODICE_HASH=8004
    depends_on:
      - registration_server
    networks:
      - mynetwork
networks:
  mynetwork:
   name: network1234
